"""empty message

Revision ID: 0b696781410c
Revises: c738f8dfb7b6
Create Date: 2019-12-12 12:47:51.346488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b696781410c'
down_revision = 'c738f8dfb7b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('gender', sa.Integer(), nullable=True))
    op.add_column('client', sa.Column('military', sa.Integer(), nullable=True))
    op.add_column('client', sa.Column('race', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'race')
    op.drop_column('client', 'military')
    op.drop_column('client', 'gender')
    # ### end Alembic commands ###
