"""empty message

Revision ID: 86f6ed7be4cd
Revises: ff8fbb4b0b14
Create Date: 2019-12-11 10:17:42.727526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f6ed7be4cd'
down_revision = 'ff8fbb4b0b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
